export const itemImages = require.context("./", true);
export const itemSounds = require.context("./", true);

export const exploreInfo = [
  {
    id: 1,
    name: "John Doe",
    title: "Item Title",
    price: "0.028 ETH",
    bid: "0.12 ETH",
    src: "./profPic.png",
    musicSrc: "./sexOnFire.mp3",
  },
  {
    id: 2,
    name: "John Doe",
    title: "Item Title",
    price: "0.028 ETH",
    bid: "0.12 ETH",
    src: "./profPic.png",
    musicSrc: "./sexOnFire.mp3",
  },
  {
    id: 3,
    name: "John Doe",
    title: "Item Title",
    price: "0.028 ETH",
    bid: "0.12 ETH",
    src: "./profPic.png",
    musicSrc: "./sexOnFire.mp3",
  },
  {
    id: 4,
    name: "John Doe",
    title: "Item Title",
    price: "0.028 ETH",
    bid: "0.12 ETH",
    src: "./profPic.png",
    musicSrc: "./sexOnFire.mp3",
  },
  {
    id: 5,
    name: "John Doe",
    title: "Item Title",
    price: "0.028 ETH",
    bid: "0.12 ETH",
    src: "./profPic.png",
    musicSrc: "./sexOnFire.mp3",
  },
  {
    id: 6,
    name: "John Doe",
    title: "Item Title",
    price: "0.028 ETH",
    bid: "0.12 ETH",
    src: "./profPic.png",
    musicSrc: "./sexOnFire.mp3",
  },
  {
    id: 7,
    name: "John Doe",
    title: "Item Title",
    price: "0.028 ETH",
    bid: "0.12 ETH",
    src: "./profPic.png",
    musicSrc: "./sexOnFire.mp3",
  },
  {
    id: 8,
    name: "John Doe",
    title: "Item Title",
    price: "0.028 ETH",
    bid: "0.12 ETH",
    src: "./profPic.png",
    musicSrc: "./sexOnFire.mp3",
  },
  {
    id: 9,
    name: "John Doe",
    title: "Item Title",
    price: "0.028 ETH",
    bid: "0.12 ETH",
    src: "./profPic.png",
    musicSrc: "./sexOnFire.mp3",
  },
  {
    id: 10,
    name: "John Doe",
    title: "Item Title",
    price: "0.028 ETH",
    bid: "0.12 ETH",
    src: "./profPic.png",
    musicSrc: "./sexOnFire.mp3",
  },
];
