import { users } from "./Users";

export const itemImages = require.context("../src/images", true);
export const itemSounds = require.context("../src/sounds", true);

export const exploreInfo = [
  {
    id: 0,
    userId: 0,
    name: users[0].name,
    avatar: './profPic.png',
    title: 'Trumpet 🎺',
    price: '0.28',
    thumbnail: './trumpet.jpg',
    sound: './trumpet.wav',
    desc: "Ut placerat magna auctor, scelerisque risus a, mattis ante. Suspendisse at varius lorem. Phasellus tincidunt eros eget sem pulvinar, ultrices finibus lorem ultrices. Sed tempor, massa nec rhoncus placerat, ex erat facilisis lorem, vitae semper dui libero sed lacus. Donec ultricies urna ac lectus porta, id egestas risus elementum. Sed sagittis tellus leo. Ut eget massa lacus. Nulla ut enim eget urna pretium condimentum. Maecenas velit eros, venenatis sed blandit et, condimentum ut enim. Fusce blandit, ipsum et condimentum vehicula, mauris turpis aliquet lectus, rutrum pretium lacus lacus vitae purus. Nunc molestie metus at est tempus hendrerit.",
    key: 0
  },
  {
    id: 0,
    userId: 0,
    name: users[0].name,
    avatar: './profPic.png',
    title: 'Movie Trailer',
    price: '31.8',
    thumbnail: './movie.jpg',
    sound: './movie-trailer.mp3',
    desc: "Aliquam maximus justo ut velit vehicula semper. Quisque ut turpis in nunc consequat porta. Donec tempus laoreet aliquet. Nulla tincidunt augue sit amet odio mollis, a congue augue mattis. Quisque a massa ut lorem pretium efficitur. Phasellus euismod vitae ante sit amet porta. Fusce eu semper ante, euismod varius nisi. Donec augue nunc, tempor eget massa ac, ullamcorper luctus dui. Nam placerat risus est, non posuere diam dignissim sed. Etiam tempus, nulla et auctor accumsan, purus purus elementum magna, et congue mi erat sit amet arcu. Pellentesque et eleifend nulla. Integer pulvinar justo dapibus, tempor mauris eu, dictum nulla. Pellentesque ac nisi sapien. Vestibulum pellentesque ipsum a mauris ultricies congue. Pellentesque et augue pharetra, egestas massa in, molestie mi. Duis leo tellus, malesuada sed mollis sed, facilisis vel lorem.",
    key: 1,
  },
  {
    id: 2,
    name: users[2].name,
    userId: 2,
    avatar: './profPic2.png',
    title: 'Bubbles',
    price: '3.54',
    thumbnail: './beer.jpg',
    sound: './beer.mp3',
    desc: 'Cras sed gravida ante, eget maximus augue. In vulputate facilisis elit, sed condimentum turpis egestas et. Phasellus nec iaculis ligula. In eleifend libero sed felis lobortis, et laoreet eros facilisis. In hac habitasse platea dictumst. Mauris quis eros id risus sollicitudin mollis. Mauris pulvinar scelerisque lacus, sed fermentum mauris. Nunc at gravida quam, non iaculis mauris. Nulla non sem at leo porta porta eget auctor justo.',
    key: 3,
  },
  {
    id: 3,
    name: users[3].name,
    userId: 3,
    avatar: './profPic.png',
    title: 'Chill',
    price: '74',
    thumbnail: './chill.jpg',
    sound: './chill.mp3',
    desc: 'Vestibulum commodo vehicula arcu eu consectetur.Sed tincidunt augue leo, id tincidunt nunc placerat id.Nunc porta lacus urna, vitae pellentesque nisl fermentum at.Fusce vel ex ut lorem commodo pharetra.Pellentesque pellentesque lorem lorem, ut fringilla eros egestas quis.Nulla facilisi.Vivamus ut dignissim sem, eu ullamcorper justo.Pellentesque consequat scelerisque augue.Ut porttitor condimentum odio, eget venenatis purus rutrum eget.Cras accumsan dolor sed nulla tincidunt, volutpat tristique diam consequat.',
    key: 5,
  },
  {
    id: 5,
    name: users[5].name,
    userId: 5,
    avatar: './profPic.png',
    title: 'Loop',
    price: '31.8',
    thumbnail: './loop.jpg',
    sound: './loop.mp3',
    desc: 'Vivamus faucibus mi at elit volutpat, et porta sem blandit. In volutpat sem sed suscipit finibus. Nullam et lacinia diam. Curabitur vel malesuada sapien. Nam porttitor mauris dolor, sit amet fermentum dui pharetra vel. Fusce molestie consequat commodo. Quisque laoreet eros lectus, a mattis ligula tristique id. Nullam non lectus pharetra, lobortis ipsum sed, egestas nisi. Nullam finibus tellus in magna molestie congue. Morbi volutpat leo ac turpis pulvinar consequat. Morbi tincidunt aliquet erat eget laoreet.',
    key: 10,
  },
  {
    id: 3,
    name: users[3].name,
    userId: 3,
    avatar: './profPic.png',
    title: 'Classic',
    price: '68',
    thumbnail: './classic.jpg',
    sound: './classic.mp3',
    desc: 'Donec id sapien ac tortor eleifend euismod at id nibh. Sed iaculis, metus ac dignissim iaculis, metus est vehicula diam, quis imperdiet purus tortor ut enim. Maecenas vitae rutrum purus. Donec vitae lorem id libero molestie mattis. Nulla faucibus at turpis a efficitur. Maecenas id dui ut lorem tempus egestas non sit amet tellus. Pellentesque sed orci id massa faucibus semper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi mattis rhoncus ligula a gravida. In sed arcu pellentesque lacus fermentum dignissim ut et sapien. Aliquam finibus sem vel sagittis sodales. Vestibulum massa nulla, imperdiet in velit a, laoreet cursus mauris.',
    key: 6,
  },

  {
    id: 6,
    name: users[6].name,
    userId: 6,
    avatar: './profPic3.png',
    title: 'Rock',
    price: '7.8',
    thumbnail: './rock.jpg',
    sound: './rock.mp3',
    desc: 'Ut porta metus sit amet sem maximus aliquam ut at urna. Pellentesque tristique ipsum vel scelerisque accumsan. Sed bibendum arcu eu felis rutrum, vel rutrum ipsum finibus. Curabitur efficitur pharetra dolor vel fermentum. Phasellus at mattis turpis. Ut porttitor, eros eu aliquet convallis, dui eros vulputate diam, sed dictum neque mi et purus. Aliquam erat volutpat. Fusce vel velit arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras interdum aliquam purus, nec hendrerit eros finibus id. Aliquam commodo, ex ut faucibus rutrum, leo est faucibus lorem, id lobortis arcu neque non dui. Duis neque dolor, aliquet sit amet semper at, fermentum vel ante. Morbi imperdiet vestibulum pharetra.',
    key: 12,
  },
  {
    id: 4,
    name: users[4].name,
    userId: 4,
    avatar: './profPic4.png',
    title: 'Goat Bell',
    price: '31.8',
    thumbnail: './goat-bell.jpg',
    sound: './goat-bell.mp3',
    desc: 'Aliquam maximus justo ut velit vehicula semper. Quisque ut turpis in nunc consequat porta. Donec tempus laoreet aliquet. Nulla tincidunt augue sit amet odio mollis, a congue augue mattis. Quisque a massa ut lorem pretium efficitur. Phasellus euismod vitae ante sit amet porta. Fusce eu semper ante, euismod varius nisi. Donec augue nunc, tempor eget massa ac, ullamcorper luctus dui. Nam placerat risus est, non posuere diam dignissim sed. Etiam tempus, nulla et auctor accumsan, purus purus elementum magna, et congue mi erat sit amet arcu. Pellentesque et eleifend nulla. Integer pulvinar justo dapibus, tempor mauris eu, dictum nulla. Pellentesque ac nisi sapien. Vestibulum pellentesque ipsum a mauris ultricies congue. Pellentesque et augue pharetra, egestas massa in, molestie mi. Duis leo tellus, malesuada sed mollis sed, facilisis vel lorem.',
    key: 8,
  },
  {
    id: 4,
    name: users[4].name,
    userId: 4,
    avatar: './profPic4.png',
    title: 'Spin',
    price: '31.8',
    thumbnail: './intro.jpg',
    sound: './intro.mp3',
    desc: 'Cras sed gravida ante, eget maximus augue. In vulputate facilisis elit, sed condimentum turpis egestas et. Phasellus nec iaculis ligula. In eleifend libero sed felis lobortis, et laoreet eros facilisis. In hac habitasse platea dictumst. Mauris quis eros id risus sollicitudin mollis. Mauris pulvinar scelerisque lacus, sed fermentum mauris. Nunc at gravida quam, non iaculis mauris. Nulla non sem at leo porta porta eget auctor justo.',
    key: 81
  },
  {
    id: 5,
    name: users[5].name,
    userId: 5,
    avatar: './profPic.png',
    title: 'Jungle',
    price: '0.55',
    thumbnail: './jungle.jpg',
    sound: './jungle.mp3',
    desc: 'Donec a sem condimentum, eleifend nisi non, ullamcorper tellus. Nam sollicitudin lobortis sem, eget facilisis libero luctus at. Morbi suscipit tellus est, ut pulvinar neque tincidunt ac. Proin venenatis mollis nibh, eget molestie nulla rutrum in. Praesent ut massa sit amet nibh congue congue. Suspendisse hendrerit, purus non cursus sodales, ex lorem commodo felis, eu suscipit ante dui ac leo. Etiam ut orci molestie, scelerisque dolor a, consequat arcu. Suspendisse eu tempor nibh, eget condimentum dui. Praesent vitae justo eu diam faucibus lobortis. Etiam eros diam, commodo quis lorem et, congue tincidunt lorem. Mauris imperdiet, lorem sit amet bibendum sollicitudin, nisl ligula facilisis eros, eleifend facilisis purus nulla id felis. Fusce vel varius arcu, sed pellentesque orci. Proin nec quam leo. Mauris vulputate ac nulla eget fermentum. Ut consectetur tincidunt congue. Nam auctor massa a neque consequat, et commodo erat volutpat.',
    key: 9,
  },
  {
    id: 6,
    name: users[6].name,
    userId: 6,
    avatar: './profPic3.png',
    title: 'Mystique',
    price: '0.55',
    thumbnail: './mystique.jpg',
    sound: './mystique.mp3',
    desc: 'Nam sit amet interdum ante. Mauris finibus, enim vitae sollicitudin tincidunt, turpis justo pretium mauris, non pulvinar ante nisi nec orci. Curabitur elementum leo nec nisl eleifend vehicula. Aenean vitae urna in tellus sodales viverra. Sed tempus mi vitae pharetra congue. Suspendisse posuere sapien eget mi lobortis, non cursus elit aliquam. Nullam in sagittis mi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
    key: 11,
  },
  {
    id: 2,
    name: users[2].name,
    userId: 2,
    avatar: './profPic2.png',
    title: 'Cheers 🙌',
    price: '14',
    thumbnail: './cheers.png',
    sound: './cheers.wav',
    desc: 'Maecenas magna nulla, blandit at nisi in, vulputate ullamcorper velit. Curabitur at porta libero. Vestibulum consequat rhoncus velit faucibus rutrum. Donec porttitor eget ipsum vitae ultricies. Pellentesque cursus scelerisque elit, non tempor ex pharetra vitae. Nulla ultrices tristique condimentum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    key: 4,
  },
  {
    id: 7,
    name: users[7].name,
    userId: 7,
    avatar: './profPic.png',
    title: 'Stadium',
    price: '3.55',
    thumbnail: './stadium.jpg',
    sound: './stadium.wav',
    desc: 'Aliquam quam metus, pulvinar nec dictum non, tempus at magna. Sed vulputate mi velit, ac ultrices nisl viverra vel. Phasellus ac posuere lectus, in dignissim elit. Donec condimentum, arcu dictum tincidunt pulvinar, tellus enim gravida libero, non placerat orci magna et lorem. Donec mattis commodo tempus. Mauris ultrices lectus sed elit euismod, nec lobortis quam porttitor. Morbi at dui condimentum, fringilla dolor eget, gravida massa. Praesent pharetra dui vitae purus elementum, eu mollis urna pretium. Fusce enim nisl, euismod ut risus eu, commodo lacinia ex. Cras orci leo, eleifend id interdum ac, imperdiet quis mauris. Cras purus ipsum, dapibus sed bibendum ut, vehicula eget nunc. Sed a dui ut felis volutpat ullamcorper ac sed tortor. Cras fermentum eu felis eget condimentum. Curabitur mi tortor, elementum eu lacinia quis, rutrum et mauris. Vivamus vulputate, ante ut consequat eleifend, ligula mi rutrum nisi, ac porttitor magna magna mattis magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
    key: 13,
  },
  {
    id: 4,
    name: users[4].name,
    userId: 4,
    avatar: './profPic4.png',
    title: 'Cricket',
    price: '0.55',
    thumbnail: './cricket.jpg',
    sound: './cricket.mp3',
    desc: 'Donec mattis arcu mi, tristique sodales turpis ultricies vel. Nullam nec mi non turpis lobortis sollicitudin non non lorem. Donec ornare felis in justo feugiat tristique. Sed at purus pharetra diam vehicula mattis. Nullam sed rutrum magna. Ut neque nisl, maximus vel nunc vitae, cursus cursus est. Vestibulum mauris mauris, ultricies ut enim maximus, efficitur venenatis ante.',
    key: 7,
  },
  {
    id: 7,
    name: users[7].name,
    userId: 7,
    avatar: './profPic.png',
    title: 'Sunrise',
    price: '31.8',
    thumbnail: './sunrise.jpg',
    sound: './sunrise.mp3',
    desc: 'Vestibulum nec condimentum erat. Phasellus mollis commodo molestie. Morbi nec congue tellus, a pellentesque massa. Sed faucibus id justo a euismod. Morbi feugiat justo et lacus hendrerit, at tempor neque pulvinar. Fusce rutrum, felis vitae bibendum sodales, ante mauris aliquet libero, a fermentum nunc enim id metus. Quisque non nibh quis ligula fringilla semper at sit amet odio. Nunc porttitor mauris vel eros placerat interdum. Sed nunc nunc, hendrerit eu nisl eget, dapibus cursus lorem. Pellentesque nec mauris finibus, rutrum elit sed, lobortis leo. Donec blandit urna a nisi efficitur lacinia. Nullam consectetur fermentum nunc, eget malesuada lorem rhoncus eu. Sed a mollis tellus, vehicula ullamcorper urna. Ut semper, lacus sit amet varius malesuada, massa nisl pulvinar augue, id hendrerit sapien urna eu dui.',
    key: 14,
  },
  {
    id: 8,
    name: users[8].name,
    userId: 8,
    avatar: './profPic.png',
    title: 'Timer',
    price: '42',
    thumbnail: './timer.jpg',
    sound: './timer.wav',
    desc: 'Maecenas et eleifend elit, vel fringilla mauris. In tempus ultrices pretium. Donec viverra felis id elementum sagittis. Maecenas nec euismod ligula. Quisque nulla sapien, convallis et ultricies ut, laoreet nec erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nunc gravida ex non est luctus placerat. Aliquam sit amet augue at neque tempor viverra ut quis massa. Aliquam neque felis, faucibus mollis vestibulum ut, pulvinar et dui. Nulla vulputate felis est, id eleifend tortor lacinia quis.',
    key: 15,
  },
  {
    id: 8,
    name: users[8].name,
    userId: 8,
    avatar: './profPic.png',
    title: 'Town',
    price: '31.8',
    thumbnail: './town.jpg',
    sound: './town.mp3',
    desc: 'Duis ac nunc dapibus, ultricies libero et, faucibus erat. Proin sit amet dui id risus posuere vestibulum. Cras ut purus turpis. Vestibulum condimentum, arcu vitae porta pulvinar, elit arcu suscipit felis, a semper risus arcu quis urna. Integer sollicitudin vulputate congue. Aenean non urna mauris. Quisque sed dolor felis. Mauris sit amet congue purus. Morbi at dui lacus. Aliquam erat volutpat. Quisque porta ex sit amet sapien aliquet, vitae aliquet turpis tempus. Nulla ullamcorper enim velit, ac ornare mi bibendum eget. Maecenas ultricies rutrum erat et ornare. Integer nec risus ut neque hendrerit vestibulum. Vestibulum eget nunc libero.',
    key: 16,
  },
  {
    id: 9,
    name: users[9].name,
    userId: 9,
    avatar: './profPic2.png',
    title: 'Uplifting 🎉',
    price: '0.48',
    thumbnail: './uplifting.jpg',
    sound: './uplifting.mp3',
    desc: 'In posuere fermentum consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed non nibh bibendum, eleifend lacus at, rhoncus velit. Nam sollicitudin turpis id volutpat semper. Aliquam et mattis mauris, at venenatis nunc. Pellentesque eget tortor finibus, ornare mi vel, interdum velit. Phasellus tempor faucibus enim, eu vulputate velit fermentum at. Curabitur a orci quam. Vestibulum mollis nulla leo, eget ornare nisi consequat dictum.',
    key: 17,
  },
  {
    id: 9,
    name: users[9].name,
    userId: 9,
    avatar: './profPic2.png',
    title: 'Wilderness',
    price: '61',
    thumbnail: './wilderness.jpg',
    sound: './wilderness.wav',
    desc: 'Nullam id tellus ac neque molestie gravida. Suspendisse commodo nisl sed finibus facilisis. Maecenas vel libero ex. Aliquam scelerisque elit et nunc tincidunt, vitae pellentesque ipsum porta. In vel urna et ex pharetra fermentum. Nam non maximus nibh. Nam nunc enim, aliquet vitae commodo vel, finibus ultrices nulla. Maecenas cursus pulvinar ullamcorper.',
    key: 18,
  },
  {
    id: 1,
    userId: 1,
    name: users[1].name,
    avatar: './profPic2.png',
    title: 'Bass 🎸',
    price: '8.8',
    thumbnail: './bass.jpg',
    sound: './bass.mp3',
    desc: 'Suspendisse blandit ultricies arcu, quis eleifend odio convallis sed. Sed ut velit a lacus euismod vulputate. Etiam a justo et leo iaculis fringilla quis sit amet risus. Vivamus dapibus tempor justo. Donec fringilla enim quis rutrum efficitur. Duis malesuada pretium neque, elementum pulvinar erat interdum id. Nam sodales enim mi, quis tempus metus fringilla malesuada. Maecenas eu felis diam. Morbi sagittis tortor eu sollicitudin maximus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
    key: 2,
  },
  {
    id: 10,
    name: users[10].name,
    userId: 10,
    avatar: './profPic.png',
    title: 'Piano',
    price: '61',
    thumbnail: './piano.jpg',
    sound: './piano.mp3',
    desc: 'Aliquam sit amet velit in tellus laoreet venenatis sagittis nec dolor. Sed orci elit, viverra non fringilla vel, interdum eu turpis. Donec aliquam magna et turpis aliquet, nec placerat neque semper. Nullam eget leo porttitor, dignissim ante vel, rutrum tellus. Vivamus sed rhoncus orci. Nam gravida lorem sed mollis auctor. Fusce elementum metus eu risus blandit, at euismod nisi porta. Curabitur iaculis nisl mauris, a cursus dui hendrerit eget. Nullam urna leo, interdum sed tellus sit amet, hendrerit egestas est. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec ut venenatis urna. Pellentesque ut facilisis elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed sed placerat nisl.',
    key: 19,
  }

];