export const itemImages = require.context("./", true);
export const itemSounds = require.context("./", true);

export const exploreInfo = [
  {
    id: 1,
    name: "John Doe",
    title: "Item Title 1",
    price: "0.028 ETH",
    bid: "0.12 ETH",
    src: "./profPic.png",
    musicSrc: "./sexOnFire.mp3",
    creatorId: 1,
    rating: 5,
  },
  {
    id: 2,
    name: "John Doe",
    title: "Item Title 2",
    price: "0.028 ETH",
    bid: "0.12 ETH",
    src: "./profPic.png",
    musicSrc: "./sexOnFire.mp3",
    creatorId: 4,
    rating: 4,
  },
  {
    id: 3,
    name: "John Doe",
    title: "Item Title 3",
    price: "0.028 ETH",
    bid: "0.12 ETH",
    src: "./profPic.png",
    musicSrc: "./sexOnFire.mp3",
    creatorId: 3,
    rating: 2,
  },
  {
    id: 4,
    name: "John Doe",
    title: "Item Title 4",
    price: "0.023 ETH",
    bid: "0.12 ETH",
    src: "./profPic.png",
    musicSrc: "./sexOnFire.mp3",
    creatorId: 1,
    rating: 3,
  },
  {
    id: 5,
    name: "John Doe",
    title: "Item Title 5",
    price: "0.014 ETH",
    bid: "0.12 ETH",
    src: "./profPic.png",
    musicSrc: "./sexOnFire.mp3",
    creatorId: 1,
    rating: 4,
  },
  {
    id: 6,
    name: "John Doe",
    title: "Item Title 6",
    price: "0.028 ETH",
    bid: "0.12 ETH",
    src: "./profPic.png",
    musicSrc: "./sexOnFire.mp3",
    creatorId: 2,
    rating: 4,
  },
  {
    id: 7,
    name: "John Doe",
    title: "Item Title 7",
    price: "0.030 ETH",
    bid: "0.12 ETH",
    src: "./profPic.png",
    musicSrc: "./sexOnFire.mp3",
    creatorId: 1,
    rating: 3,
  },
  {
    id: 8,
    name: "John Doe",
    title: "Item Title 8",
    price: "0.028 ETH",
    bid: "0.12 ETH",
    src: "./profPic.png",
    musicSrc: "./sexOnFire.mp3",
    creatorId: 4,
    rating: 1,
  },
  {
    id: 9,
    name: "John Doe",
    title: "Item Title 9",
    price: "0.028 ETH",
    bid: "0.12 ETH",
    src: "./profPic.png",
    musicSrc: "./sexOnFire.mp3",
    creatorId: 2,
    rating: 4,
  },
  {
    id: 10,
    name: "John Doe",
    title: "Item Title 10",
    price: "0.028 ETH",
    bid: "0.12 ETH",
    src: "./profPic.png",
    musicSrc: "./sexOnFire.mp3",
    creatorId: 2,
    rating: 2,
  },
];
