export const profImages = require.context("./", true);

export const peopleInfo = [
  {
    id: 1,
    name: "John Doe1",
    sold: "1000",
    src: "./profPic.png",
    musicSrc: "./sexOnFire.mp3",
    itemCount: 4,
  },
  {
    id: 2,
    name: "John Doe2",
    sold: "1500",
    src: "./profPic2.png",
    musicSrc: "./sexOnFire.mp3",
    itemCount: 12,
  },
  {
    id: 3,
    name: "John Doe3",
    sold: "1030",
    src: "./profPic3.png",
    musicSrc: "./sexOnFire.mp3",
    itemCount: 8,
  },
  {
    id: 4,
    name: "John Doe4",
    sold: "1200",
    src: "./profPic4.png",
    musicSrc: "./sexOnFire.mp3",
    itemCount: 2,
  },
  {
    id: 5,
    name: "John Doe5",
    sold: "1008",
    src: "./profPic.png",
    itemCount: 10,
  },
  {
    id: 6,
    name: "John Doe6",
    sold: "1045",
    src: "./profPic3.png",
    itemCount: 11,
  },
  {
    id: 7,
    name: "John Doe7",
    sold: "1830",
    src: "./profPic2.png",
    itemCount: 7,
  },
  {
    id: 8,
    name: "John Doe8",
    sold: "3600",
    src: "./profPic.png",
    itemCount: 3,
  },
  {
    id: 9,
    name: "John Doe9",
    sold: "85500",
    src: "./profPic4.png",
    itemCount: 4,
  },
  {
    id: 10,
    name: "John Doe10",
    sold: "73000",
    src: "./profPic.png",
    itemCount: 14,
  },
  {
    id: 11,
    name: "John Doe11",
    sold: "7000",
    src: "./profPic3.png",
    itemCount: 6,
  },
  {
    id: 12,
    name: "John Doe12",
    sold: "8500",
    src: "./profPic4.png",
    itemCount: 2,
  },
];
